version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Compile front-end code
          command: |
            cd ./frontend/
            npm i
            npm run build
    
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Compile back-end code
          command: |
            cd ./backend/
            npm i
            npm run build
      
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
